name: fluttercommerce
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: libraries/core
  navigation:
    path: libraries/navigation
  widgets:
    path: libraries/widgets
  network:
    path: libraries/network

  cupertino_icons: ^1.0.4
  cached_network_image: ^3.1.0+1
  shimmer: ^2.0.0
  package_info: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  freezed: ^1.0.0
  firebase_crashlytics: ^2.3.0

  #  razorpay_flutter: ^1.2.7
  country_code_picker: ^2.0.2
  build_web_compilers: ^3.2.2
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#dependency_overrides:
#  analyzer:
#  meta:
#  build_resolvers:
## The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    #Images
    - assets/images/app_logo.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700