name: fluttercommerce
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.0.15
  get_it: ^7.2.0
  auto_route: ^3.1.3
  cupertino_icons: ^1.0.4
  connectivity: ^3.0.6
  cached_network_image: ^3.1.0+1
  json_annotation: ^4.3.0
  shimmer: ^2.0.0
  package_info: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  freezed: ^1.0.0
  flutter_bloc: ^8.0.0
  cloud_firestore: ^3.1.0
  firebase_crashlytics: ^2.3.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
#  razorpay_flutter: ^1.2.7
  country_code_picker: ^2.0.2
  build_web_compilers: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  auto_route_generator: ^3.1.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
#dependency_overrides:
#  analyzer:
#  meta:
#  build_resolvers:
## The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    #Images
    - assets/images/app_logo.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700