name: fluttercommerce
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.1.0
  freezed_annotation: ^2.1.0
  #Firebase
  firebase_core: ^1.10.0
  core:
    path: ../core
  domain:
    path: ../domain
  presentation:
    path: ../presentation
  data:
    path: ../data
  localization:
    path: ../localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics:
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  injectable_generator: ^2.1.3


dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:
