name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.0
  encrypt: ^5.0.1
  logger: ^1.1.0
  flutter_bloc: ^8.0.0
  intl: ^0.18.0
  url_launcher: ^6.0.15
  shared_preferences: ^2.2.0
  flutter_easyloading: 3.0.5
  flutter_spinkit: ^5.2.0
  shared_dependencies:
    path: ../shared_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  injectable_generator: ^2.1.6

flutter: