name: Ecomm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: flutter build apk


