name: Ecomm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - run: flutter pub global activate melos
      - run: melos analyze
      - run: melos get
      - run: melos build

