name: Ecomm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 19.0.1
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'
          channel: 'stable'
      - run: flutter pub global activate melos
      - run: melos analyze
      - run: melos get
      - run: melos generateAll
      - run: melos localization
      - run: melos build

