name: Ecomm

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    environment:
      name: 'Prod'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: 'stable'
          cache: true
      - name: 🔐 Retrieve base64 keystore and decode it to a file
        env:
            KEYSTORE_BASE64: ${{ secrets.FIREKART_KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > "${{ github.workspace }}/firekart.keystore"
      - name: 📝🔐 Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/android/app/keystore.properties
        run: |
          echo 'storeFile=${{ github.workspace }}/firekart.keystore' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyAlias=${{ secrets.KEYALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'storePassword=${{ secrets.STOREPASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyPassword=${{ secrets.KEYPASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n
      - run: flutter test --no-pub --coverage
      - run: flutter build apk --verbose
      - run: flutter build ios --release --no-codesign

